# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Journal articles
    url: /#papers
  - name: Working papers
    url: /#papers
    weight: 11
  - name: Reports
    url: /#reports
    weight: 12
  - name: CV
    url: /files/cv.pdf
    weight: 20
  - name: Publications
    url: publications/
    weight: 30
